organization/urls.py
from django.conf.urls import url
from . import views

app_name = 'organization'

urlpatterns = [

# this is most common url pattern index which go to home area
    url(r'^$', views.index, name='index'),
    # when url connect with start like 8000/organization/start
    #  then it response with view.py class name start
    url(r'^start$', views.start, name='start'),

    # this is also same way work how a start is work their
    url(r'^about/$', views.about, name='about'),
    # this is work on register work in user 
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<organization_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<special_event_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^special_events/(?P<filter_by>[a-zA_Z]+)/$', views.special_events, name='special_events'),
       # (?P<organization_id>[0-9]+ this is actually work a unique user id on their which is
       #  represent any 0-9 number
    url(r'^create_organization/$', views.create_organization, name='create_organization'),
    url(r'^(?P<organization_id>[0-9]+)/create_special_event/$', views.create_special_event, name='create_special_event'),
    url(r'^(?P<organization_id>[0-9]+)/delete_special_event/(?P<special_event_id>[0-9]+)/$', views.delete_special_event, name='delete_special_event'),
    url(r'^(?P<organization_id>[0-9]+)/favorite_organization/$', views.favorite_organization, name='favorite_organization'),
    url(r'^(?P<organization_id>[0-9]+)/delete_organization/$', views.delete_organization, name='delete_organization'),
    url(r'^(?P<organization_id>[0-9]+)/event_detail/$', views.event_detail, name='event_detail'),


]

web/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^organization/', include('organization.urls')),
    url(r'^', include('organization.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organization/models.py
from django.contrib.auth.models import Permission, User
from django.db import models

# this table for Organization in heir user is reprent id which default value is 1
class Organization(models.Model):
    user = models.ForeignKey(User, default=1)
    established = models.CharField(max_length=250)
    organization_name = models.CharField(max_length=500)
    organization_type = models.CharField(max_length=100)
    organization_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.organization_name + ' - ' + self.established

 # this is another table where many event information attach their 
class Special_event(models.Model):
    # in here organization is connect with another Organization table 
    # with ForeignKey key this is most important part of database design
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    date = models.CharField(max_length=500)
    time =models.CharField(max_length=200)
    topic = models.CharField(max_length=20000)
    location = models.CharField(max_length=500)
    event_detail = models.CharField(max_length=500)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.topic + '-'+ self.time + '-'+ self.location


# model.py  is mainly use for organize a table structure on that occasion 

organization/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Organization, Special_event

# in here which type of data output on this section of table  
# that is select by fields and add the model name on their
class OrganizationForm(forms.ModelForm):

    class Meta:
        model = Organization
        fields = ['established', 'organization_name', 'organization_type', 'organization_logo']


class Special_eventForm(forms.ModelForm):

    class Meta:
        model = Special_event
        fields = ['topic', 'date']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

organization/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import OrganizationForm, Special_eventForm, UserForm
from .models import Organization, Special_event

# AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']


# this is represent which type of image file alow to run progrrame
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

 # add organization in section work properly
def create_organization(request):
    if not request.user.is_authenticated():
        return render(request, 'organization/login.html')
    else:
        form = OrganizationForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            organization = form.save(commit=False)
            organization.user = request.user
            organization.organization_logo = request.FILES['organization_logo']
            file_type = organization.organization_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'organization': organization,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'organization/create_organization.html', context)
            organization.save()
            return render(request, 'organization/detail.html', {'organization': organization})
        context = {
            "form": form,
        }
        return render(request, 'organization/create_organization.html', context)

# this is a section which is active when i want to input information data 
# as organization event update
# which is control by admin pannel .it is off nonal way
def create_special_event(request, organization_id):
    form = special_eventForm(request.POST or None, request.FILES or None)
    organization = get_object_or_404(Organization, pk=organization_id)
    if form.is_valid():
        organizations_special_events = organization.special_event_set.all()
        for s in organizations_special_events :
            if s.topic == form.cleaned_data.get("special_event_topic"):
                context = {
                    'organization': organization,
                    'form': form,
                    'error_message': 'You already added that special_event',
                }
                return render(request, 'organization/create_special_event.html', context)
        special_event = form.save(commit=False)
        special_event.organization = organization
        # special_event.audio_file = request.FILES['audio_file']
        # file_type = special_event.audio_file.url.split('.')[-1]
        # file_type = file_type.lower()
        # if file_type not in AUDIO_FILE_TYPES:
        #     context = {
        #         'organization': organization,
        #         'form': form,
        #         'error_message': 'Audio file must be WAV, MP3, or OGG',
        #     }
        #     return render(request, 'organization/create_special_event.html', context)

        special_event.save()
        return render(request, 'organization/detail.html', {'organization': organization})
    context = {
        'organization': organization,
        'form': form,
    }
    return render(request, 'organization/create_special_event.html', context)



# this porsion is show the organization event detail in table click page
# go to a new page and update many different field

def event_detail(request,organization_id):
    if not request.user.is_authenticated():
        return render(request, 'organization/login.html')
    else:
        user = request.user
        organization = get_object_or_404(Organization, pk=organization_id)
        return render(request, 'organization/event_detail.html', {'organization': organization, 'user': user})

# this thing is work in all organization when i want to 
# remove a particular organization on that area

def delete_organization(request, organization_id):
    organization = Organization.objects.get(pk=organization_id)
    organization.delete()
    organizations = Organization.objects.filter(user=request.user)
    return render(request, 'organization/index.html', {'organizations': organizations})

# this section allow remove event update on that occasion this part is 
# delect option is work their
def delete_special_event(request, organization_id, special_event_id):
    organization = get_object_or_404(organization, pk=organization_id)
    special_event = Special_event.objects.get(pk=special_event_id)
    special_event.delete()
    return render(request, 'organization/detail.html', {'organization': organization})
 # this section is related with the detail update on any organization event 
 # update their

def detail(request, organization_id):
    if not request.user.is_authenticated():
        return render(request, 'organization/login.html')
    else:
        user = request.user
        organization = get_object_or_404(Organization, pk=organization_id)
        return render(request, 'organization/detail.html', {'organization': organization, 'user': user})

 # this section is represt the important section which is motivate
 # which organization is particularly important on that section is automaticlly 
 # start button
def favorite(request, special_event_id):
    special_event = get_object_or_404(Special_event, pk=special_event_id)
    try:
        if special_event.is_favorite:
            special_event.is_favorite = False
        else:
            special_event.is_favorite = True
        special_event.save()
    except (KeyError, Special_event.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def favorite_organization(request, organization_id):
    organization = get_object_or_404(Organization, pk=organization_id)
    try:
        if organization.is_favorite:
            organization.is_favorite = False
        else:
            organization.is_favorite = True
        organization.save()
    except (KeyError, Organization.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'organization/login.html')
    else:
        organizations = Organization.objects.filter(user=request.user)
        special_event_results = Special_event.objects.all()
        query = request.GET.get("q")
        if query:
            organizations = organizations.filter(
                Q(organization_name__icontains=query) |
                Q(established__icontains=query)
            ).distinct()
            special_event_results =special_event_results.filter(
                Q(topic__icontains=query)
            ).distinct()
            return render(request, 'organization/index.html', {
                'organizations': organizations,
                'special_events': special_event_results,
            })
        else:
            return render(request, 'organization/index.html', {'organizations': organizations})

def about(request):
    return render(request,'organization/about.html')


def start(request):
    if not request.user.is_authenticated():
        return render(request, 'organization/login.html')
    else:
        organizations = Organization.objects.filter(user=request.user)
        special_event_results = Special_event.objects.all()
        query = request.GET.get("q")
        if query:
            organizations = organizations.filter(
                Q(organization_name__icontains=query) |
                Q(established__icontains=query)
            ).distinct()
            special_event_results =special_event_results.filter(
                Q(topic__icontains=query)
            ).distinct()
            return render(request, 'organization/start.html', {
                'organizations': organizations,
                'special_events': special_event_results,
            })
        else:
            return render(request, 'organization/start.html', {'organizations': organizations})




def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'organization/login.html', context)

# this is section 
def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                organizations = Organization.objects.filter(user=request.user)
                return render(request, 'organization/index.html', {'organizations': organizations})
            else:
                return render(request, 'organization/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'organization/login.html', {'error_message': 'Invalid login'})
    return render(request, 'organization/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                organizations = Organization.objects.filter(user=request.user)
                return render(request, 'organization/index.html', {'organizations': organizations})
    context = {
        "form": form,
    }
    return render(request, 'organization/register.html', context)

organization/templates/organization/base.html
<!-- 
This is nomarlly represent upper part of of every page on this content ..actually it represent as menu bar type
 -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}SUST EVENT PORTAL{% endblock %}</title>


   <!--  this line rrepresent the static file on this occation -->
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'organization/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'organization/js/main.js' %}"></script>
</head>

<style>
    
    h1{


        color: green;
    text-align: center;

    border-left: 7px solid red;
    background-color: lightgrey;
    }
</style>

<h1>          Sust event portal</h1>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'organization:index' %}">Home</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block organizations_active %}{% endblock %}"><a href="{% url 'organization:start' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; organizations</a></li>
                <li class="{% block special_events_active %}{% endblock %}"><a href="{% url 'organization:about'  %}"><span class="glyphicon glyphicon-organization" aria-hidden="true"></span>&nbsp; ABOUT</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'organization:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'organization:create_organization' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add organization
                    </a>
                </li>
                <li>
                    <a href="{% url 'organization:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

organization/templates/organization/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'organization/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'organization/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'organization:index' %}">Home</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'organization:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'organization:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

organization/templates/organization/detail.html
{% extends 'organization/base.html' %}
{% block title %}{{ organization }}{% endblock %}
{% block organizations_active %}active{% endblock %}

{% block body %}
<div class="container-fluid special_events-container">

    <div class="row">

        <!-- Left organization Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'organization:detail' organization.id %}">
                        {% if organization.organization_logo %}
                            <img src="{{ organization.organization_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ organization.organization_name }} <small> 

                    </br>Type: {{ organization.organization_type }}</small></h1>
                    <h2>from in: {{ organization.established }}</h2>
                </div>
            </div>
        </div>

        <!-- Right special_event Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'organization:detail' organization.id %}">View All</a></li>
                <!-- <li role="presentation"><a href="{% url 'organization:create_special_event' organization.id %}">Add New special_event</a></li> -->
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All special events</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
  <!-- this is a table for the organization event information detail -->
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Event name</th>
                            <th>time</th>
                            <th>Location</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for special_event in organization.special_event_set.all %}
                            <tr>
                                <td><a href = "/organization/{{ organization.id }}/event_detail">{{ special_event.topic }}</a></td>
                                <td>
                                    <!-- <a target="_blank" href="{{ special_event.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button> -->
                                    <!-- </a> -->


                                    {{ special_event.time }}
                                </td>

                                <td>{{ special_event.location }}</td>
                                <td>
                                    <a href="{% url 'organization:favorite' special_event.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if special_event.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'organization:delete_special_event' organization.id special_event.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="special_event_id" value="{{ special_event.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

organization/templates/organization/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="topic">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

organization/templates/organization/register.html
{% extends 'organization/base.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
 <!-- this is the registration process  for create a new user id  -->
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'organization/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'organization:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

organization/templates/organization/start.html
{% extends 'organization/base.html' %}
{% block organizations_active %}active{% endblock %}

{% block body %}


<!-- <img src="https://upload.wikimedia.org/wikipedia/en/c/c1/SUST_1_km_entrance_way.jpg"> -->
<div class="organizations-container container-fluid">

    <!-- organizations -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s organizations</h3>
        </div>
        {% if organizations %}
            {% for organization in organizations %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'organization:detail' organization.id %}">
                            <img src="{{ organization.organization_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ organization.organization_name }}</h2>
                            <h4>{{ organization.organization_type }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'organization:detail' organization.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete organization -->
                            <form action="{% url 'organization:delete_organization' organization.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="organization_id" value="{{ organization.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite organization -->
                            <a href="{% url 'organization:favorite_organization' organization.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if organization.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'organization:create_organization' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an organization
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are special_events -->
    {% if special_events %}
        <div class="row">
            <div class="col-sm-12">
                <h3>special_events</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>special_event Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>organization</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for special_event in special_events %}
                                    <tr>
                                        <td>{{ special_event.special_event_topic }}</td>
                                        <td>{{ special_event.organization.established }}</td>
                                        <td>
                                            <!-- <a target="_blank" href="{{ special_event.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a> -->
                                        </td>
                                        <td>
                                            <a href="{% url 'organization:detail' special_event.organization.id %}">
                                                <img src="{{ special_event.organization.organization_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'organization:detail' special_event.organization.id %}">{{ special_event.organization.organization_name }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'organization:favorite' special_event.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if special_event.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}